services:
  ui:
    build:
      context: .
      dockerfile: src/LocalMetrics.UI/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
    expose:
      - "8080" 
    networks:
      - localmetrics-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui
    networks:
      - localmetrics-net

networks:
  localmetrics-net:
    driver: bridge
