services:
  ui:
    build:
      context: .
      dockerfile: src/LocalMetrics.UI/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
    expose:
      - "8080" 
    networks:
      - localmetrics-net

  nginx:  
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ui
    networks:
      - localmetrics-net

networks:
  localmetrics-net:
    driver: bridge
